name: stackguardtest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore tools
      run: dotnet tool restore
    - name: Build
      run:
        cd ./tests/benchmarks/FCSBenchmarks/CompilerServiceBenchmarks && dotnet build -c Release
    - name: RunBenchmark
      run: cd ./tests/benchmarks/FCSBenchmarks/CompilerServiceBenchmarks && dotnet run --filter *
