name: stackguardtest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildwin:
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore tools
      run: dotnet tool restore
    - name: RunBenchmarkWindows
      run: ./build.cmd -configuration Release -testBenchmarks

  buildunix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore tools
      run: dotnet tool restore
    - name: fix xbit
      run: chmod +x tests/benchmarks/SmokeTestBenchmarks.sh
    - name: RunBenchmark
      run: ./build.sh --configuration Release --testBenchmarks
